version: "3"
services:
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: "./api-gateway/Dockerfile"
    depends_on:
      - server-db
    ports:
      - "3001:3001"
    volumes:
      - ./api-gateway/:/opt/app
      - /opt/app/node_modules
  server-db:
    container_name: server_db
    image: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "3101:5432"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports: 
      - "3201:80"
  client-app:
    container_name: client-app
    build:
      context: .
      dockerfile: "./client-app/Dockerfile"
    depends_on:
      - api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./client-app/:/opt/app
      - /opt/app/node_modules