version: "3"
services:
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: "./api-gateway/Dockerfile"
    ports:
      - "3001:3001"
    volumes:
      - ./api-gateway:/opt/app
  server-db:
    container_name: server_db
    image: postgres
    environment:
      POSTGRES_DB: server_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "3101:5432"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: mitchthebaker@protonmail.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports: 
      - "3201:80"