name: Run Docker Containers 
on:
  push: 
    paths:
      - ".github/workflows/run_docker_containers.yaml"
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_TOKEN:
        required: true
  workflow_dispatch:

permissions: read-all

jobs: 
  run-docker: 
    name: Run Docker 
    runs-on: ubuntu-latest 
    environment: Development
    env: 
      COMPOSE_FILE: ./docker-compose.yml
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 
      
      - name: Build .env file for api-gateway service 
        run: |
          cd ./api-gateway
          touch .env 
          echo "NODE_ENV=${{ secrets.NODE_ENV_DEV }}" >> .env
          echo "PORT=${{ secrets.NODE_PORT }}" >> .env
          echo "PG_USER=${{ secrets.PG_USER }}" >> .env
          echo "PG_HOST=${{ secrets.PG_HOST }}" >> .env
          echo "PG_DB=${{ secrets.PG_DB }}" >> .env
          echo "PG_PASSWORD=${{ secrets.PG_PASSWORD }}" >> .env
          echo "PG_PORT=${{ secrets.PG_PORT }}" >> .env
          cat .env

      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker-compose -f $COMPOSE_FILE build
          docker-compose -f $COMPOSE_FILE push

      - name: Run Docker
        run: |
          docker-compose -f $COMPOSE_FILE up -d
      
      - name: Check if client-app service is running 
        run: | 
          counter=0
          max_attempts=5

          until curl -I http://localhost:${{ secrets.REACT_PORT }} 2>/dev/null | grep -q "200 OK"; do
            if [ $counter -ge $max_attempts ]; then
                echo "Timeout reached: client-app service did not become ready in 30 seconds."
                exit 1
            fi

            echo "Waiting for client-app service to be ready..."
            sleep 5
            counter=$((counter + 1))
          done 
          echo "client-app is running!"
      
      - name: Check if api-gateway service is running 
        run: | 
          counter=0
          max_attempts=5

          until curl -I http://localhost:${{ secrets.NODE_PORT }} 2>/dev/null | grep -q "200 OK"; do
            if [ $counter -ge $max_attempts ]; then
                echo "Timeout reached: client-app service did not become ready in 30 seconds."
                exit 1
            fi

            echo "Waiting for api-gateway service to be ready..."
            sleep 5
            counter=$((counter + 1))
          done 
          echo "api-gateway is running!"

      - name: Stop Docker
        run: docker-compose -f $COMPOSE_FILE down -v