name: Run the CI/CD Pipeline 
on:
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_review:
    types: [submitted]
  push: 
    branches: 
      - "main"
  workflow_dispatch:

permissions: read-all

jobs: 
  run-docker: 
    uses: ./.github/workflows/run_docker_containers.yaml
    secrets: inherit

  e2e-tests: 
    uses: ./.github/workflows/run_e2e_tests.yaml
    secrets: inherit
    needs:
      - run-docker

  sonarcloud-analysis:
    uses: ./.github/workflows/run_sonarcloud.yaml
    secrets: inherit
  
  build:
    uses: ./.github/workflows/build_docker_containers.yaml
    secrets: inherit
    needs: 
      - run-docker
      - e2e-tests

  