name: Run the CI/CD Pipeline 
on:
  pull_request:
    types: [opened, reopened]
  pull_request_review:
    types: [submitted]
  push: 
    branches: 
      - "main"
  workflow_dispatch:

permissions: read-all

jobs: 
  checkout-repository:
    uses: actions/checkout@v4 

  run-docker: 
    uses: ./.github/workflows/run_docker_containers.yaml
    secrets: inherit

  unit-tests: 
    uses: ./.github/workflows/run_unit_tests.yaml
    needs:
      - run-docker

  sonarcloud-analysis:
    uses: ./.github/workflows/run_sonarcloud.yaml
    with: 
      ENVIRONMENT: Development
    secrets: inherit
    needs:
      - run-docker
  
  deploy-docker-images:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/actions/deploy-docker-images
    with:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ DOCKER_PASSWORD }}
      COMPOSE_FILE: ./docker-compose.yml

  