name: Run Docker Containers 
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - "main"
  pull_request_review:
    types: [submitted]
  push: 
    branches: 
      - "main"
      - "*build-ci*"

jobs: 
  run-docker: 
    name: Run Docker 
    runs-on: ubuntu-latest 
    environment: Development
    env: 
      COMPOSE_FILE: ./docker-compose.yml
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker images
        run: |
          docker-compose -f $COMPOSE_FILE build
          docker-compose -f $COMPOSE_FILE push

      - name: Run Docker
        run: |
          docker-compose -f $COMPOSE_FILE up -d
      
      - name: Wait for services to be ready
        run: |
          for i in {1..10}; do
            if curl --fail http://localhost:3000 && curl --fail http://localhost:3001 &&; then
              echo "All services are up"
              exit 0
            fi
            echo "Waiting for services to be ready..."
            sleep 10
          done
          echo "Services did not start in time"
          exit 1

      - name: Run Docker tests
        run: |
          curl http://localhost:3000
          curl http://localhost:3001

      - name: Stop Docker
        run: docker-compose -f $COMPOSE_FILE down 