name: Run Docker Containers 
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - "main"
  pull_request_review:
    types: [submitted]
  push: 
    branches: 
      - "main"
      - "*build-ci*"

jobs: 
  run-docker: 
    name: Run Docker 
    runs-on: ubuntu-latest 
    environment: Development
    env: 
      COMPOSE_FILE: ./docker-compose.yml
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Debug secrets
        run: echo "Secrets are set cool"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_USERNAME }}

      - name: Build and push Docker images
        run: |
          docker-compose -f $COMPOSE_FILE build
          docker-compose -f $COMPOSE_FILE push

      - name: Run Docker
        run: |
          docker-compose -f $COMPOSE_FILE up -d

          curl http://localhost:3000
          curl http://localhost:3001

          docker-compose -f $COMPOSE_FILE down 