name: Run the CI/CD Pipeline 
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - "main"
  pull_request_review:
    types: [submitted]
  push: 
    branches: 
      - "main"
      - "*build-ci*"
  workflow_dispatch:

permissions: read-all

jobs: 
  run-docker: 
    uses: ./.github/workflows/run_docker_containers.yaml
    with: 
      ENVIRONMENT: Development
    secrets: inherit
  unit-tests: 
    uses: ./.github/workflows/run_unit_tests.yaml
    needs:
      - run-docker
  sonarcloud-analysis:
    uses: ./.github/workflows/run_sonarcloud.yaml
    with: 
      ENVIRONMENT: Development
    secrets: inherit
    needs:
      - run-docker