name: Run E2E Tests
on:
  push:
    paths:
      - ".github/workflows/run_e2e_tests.yaml"
    branches:
      - "*-e2e-tests"
  workflow_call:
  workflow_dispatch:

permissions: read-all

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    environment: Development
    env: 
      COMPOSE_FILE: ./docker-compose.yml
      CI_COMPOSE_FILE: ./docker-compose.ci.yml
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      
      - name: Restore cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ./api-gateway
            ./client-app
            ./e2e-tests
          key: ${{ runner.os }}-cache

      - name: Build .env files
        uses: ./.github/actions/build-env
        with:
          NODE_ENV_DEV: ${{ secrets.NODE_ENV_DEV }}
          REACT_APP_API_GATEWAY_URI: ${{ secrets.REACT_APP_API_GATEWAY_URI }}
          NODE_PORT: ${{ secrets.NODE_PORT }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_HOST: ${{ secrets.PG_HOST }}
          PG_DB: ${{ secrets.PG_DB }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          PG_PORT: ${{ secrets.PG_PORT }}

      - name: Build/Run Docker
        run: |
          docker compose -f $COMPOSE_FILE -f $CI_COMPOSE_FILE build
          docker compose -f $COMPOSE_FILE -f $CI_COMPOSE_FILE up -d
  
      - name: Run Playwright tests
        run: |
          docker compose -f $COMPOSE_FILE -f $CI_COMPOSE_FILE run e2e-tests

      - name: Stop Docker
        run: docker compose -f $COMPOSE_FILE -f $CI_COMPOSE_FILE down -v
      
      - name: Save cache
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: |
            ./api-gateway
            ./client-app
            ./e2e-tests
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}