name: Run the CI/CD Pipeline 
on:
  pull_request:
    types: [opened, reopened]
  pull_request_review:
    types: [submitted]
  push: 
    branches: 
      - "main"
  workflow_dispatch:

permissions: read-all

jobs: 
  run-docker: 
    uses: ./.github/workflows/run_docker_containers.yaml
    secrets: inherit

  unit-tests: 
    uses: ./.github/workflows/run_unit_tests.yaml
    needs:
      - run-docker

  sonarcloud-analysis:
    uses: ./.github/workflows/run_sonarcloud.yaml
    with: 
      ENVIRONMENT: Development
    secrets: inherit
    needs:
      - run-docker
  
  build:
    uses: ./.github/workflows/build_docker_containers.yaml
    secrets: inherit
    needs: 
      - run-docker
      - unit-tests
      - sonarcloud-analysis

  