name: Run SBOM Scan
on:
  workflow_dispatch:
  push: 
    paths:
      - ".github/workflows/run_sbom_scan.yaml"

permissions: read-all

jobs: 
  sbom-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: philips-labs/tern-action@v1.1.0
        id: scan
        with:
          image: alpine:latest
          format: yaml
          output: sbom-artifact.yaml
      - uses: actions/upload-artifact@v4
        with:
          name: sbom-artifact 
          path: ${{ steps.scan.outputs.file }} 