name: Run E2E Tests
on:
  push:
    paths:
      - ".github/workflows/run_e2e_tests.yaml"
  workflow_call:
  workflow_dispatch:

permissions: read-all

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    environment: Development
    env: 
      COMPOSE_FILE: ./docker-compose.yml
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4 
      
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Build .env files
        uses: ./.github/actions/build-env
        with:
          NODE_ENV_DEV: ${{ secrets.NODE_ENV_DEV }}
          NODE_PORT: ${{ secrets.NODE_PORT }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_HOST: ${{ secrets.PG_HOST }}
          PG_DB: ${{ secrets.PG_DB }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          PG_PORT: ${{ secrets.PG_PORT }}
      
      - name: Build/Run Docker
        run: |
          docker-compose -f $COMPOSE_FILE build
          docker-compose -f $COMPOSE_FILE up -d
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Run Playwright tests 
        run: |
          cd ./e2e-tests
          docker images
          docker run --rm mitchthebaker/e2e-tests
      
      - name: Stop Docker
        run: docker-compose -f $COMPOSE_FILE down -v
      

    